plugins {
    id 'base'
    id 'net.neoforged.moddev' version '2.0.146' apply false
}

subprojects {
    apply plugin: 'java-library'
    group = 'ic2'
    version = rootProject.mod_version

    repositories { mavenCentral() }
    java {
        toolchain.languageVersion = JavaLanguageVersion.of(25)
        withSourcesJar()
    }
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 25
    }
    tasks.withType(AbstractArchiveTask).configureEach {
        preserveFileTimestamps = false
        reproducibleFileOrder = true
    }
}

tasks.named('build') { dependsOn ':core:build', ':neoforge:build' }
tasks.named('check') { dependsOn ':core:check', ':neoforge:check' }
tasks.named('clean') { dependsOn ':core:clean', ':neoforge:clean' }
