package ic2.neoforge.registration;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;

/** Plain crafting materials; specialized items live with their owning feature. */
public enum MaterialDefinition {
    RAW_LEAD("raw_lead", Rarity.COMMON, 64),
    RAW_TIN("raw_tin", Rarity.COMMON, 64),
    RAW_URANIUM("raw_uranium", Rarity.COMMON, 64),
    CRUSHED_COPPER("crushed_copper", Rarity.COMMON, 64),
    CRUSHED_GOLD("crushed_gold", Rarity.COMMON, 64),
    CRUSHED_IRON("crushed_iron", Rarity.COMMON, 64),
    CRUSHED_LEAD("crushed_lead", Rarity.COMMON, 64),
    CRUSHED_SILVER("crushed_silver", Rarity.COMMON, 64),
    CRUSHED_TIN("crushed_tin", Rarity.COMMON, 64),
    CRUSHED_URANIUM("crushed_uranium", Rarity.COMMON, 64),
    PURIFIED_COPPER("purified_copper", Rarity.COMMON, 64),
    PURIFIED_GOLD("purified_gold", Rarity.COMMON, 64),
    PURIFIED_IRON("purified_iron", Rarity.COMMON, 64),
    PURIFIED_LEAD("purified_lead", Rarity.COMMON, 64),
    PURIFIED_SILVER("purified_silver", Rarity.COMMON, 64),
    PURIFIED_TIN("purified_tin", Rarity.COMMON, 64),
    PURIFIED_URANIUM("purified_uranium", Rarity.COMMON, 64),
    BRONZE_DUST("bronze_dust", Rarity.COMMON, 64),
    CLAY_DUST("clay_dust", Rarity.COMMON, 64),
    COAL_DUST("coal_dust", Rarity.COMMON, 64),
    COAL_FUEL_DUST("coal_fuel_dust", Rarity.COMMON, 64),
    COPPER_DUST("copper_dust", Rarity.COMMON, 64),
    DIAMOND_DUST("diamond_dust", Rarity.COMMON, 64),
    ENERGIUM_DUST("energium_dust", Rarity.COMMON, 64),
    GOLD_DUST("gold_dust", Rarity.COMMON, 64),
    IRON_DUST("iron_dust", Rarity.COMMON, 64),
    LAPIS_DUST("lapis_dust", Rarity.COMMON, 64),
    LEAD_DUST("lead_dust", Rarity.COMMON, 64),
    LITHIUM_DUST("lithium_dust", Rarity.COMMON, 64),
    OBSIDIAN_DUST("obsidian_dust", Rarity.COMMON, 64),
    SILICON_DIOXIDE_DUST("silicon_dioxide_dust", Rarity.COMMON, 64),
    SILVER_DUST("silver_dust", Rarity.COMMON, 64),
    STONE_DUST("stone_dust", Rarity.COMMON, 64),
    SULFUR_DUST("sulfur_dust", Rarity.COMMON, 64),
    TIN_DUST("tin_dust", Rarity.COMMON, 64),
    SMALL_BRONZE_DUST("small_bronze_dust", Rarity.COMMON, 64),
    SMALL_COPPER_DUST("small_copper_dust", Rarity.COMMON, 64),
    SMALL_GOLD_DUST("small_gold_dust", Rarity.COMMON, 64),
    SMALL_IRON_DUST("small_iron_dust", Rarity.COMMON, 64),
    SMALL_LAPIS_DUST("small_lapis_dust", Rarity.COMMON, 64),
    SMALL_LEAD_DUST("small_lead_dust", Rarity.COMMON, 64),
    SMALL_LITHIUM_DUST("small_lithium_dust", Rarity.COMMON, 64),
    SMALL_OBSIDIAN_DUST("small_obsidian_dust", Rarity.COMMON, 64),
    SMALL_SILVER_DUST("small_silver_dust", Rarity.COMMON, 64),
    SMALL_SULFUR_DUST("small_sulfur_dust", Rarity.COMMON, 64),
    SMALL_TIN_DUST("small_tin_dust", Rarity.COMMON, 64),
    HYDRATED_TIN_DUST("hydrated_tin_dust", Rarity.COMMON, 64),
    NETHERRACK_DUST("netherrack_dust", Rarity.COMMON, 64),
    MIXED_METAL_INGOT("mixed_metal_ingot", Rarity.COMMON, 64),
    BRONZE_INGOT("bronze_ingot", Rarity.COMMON, 64),
    LEAD_INGOT("lead_ingot", Rarity.COMMON, 64),
    SILVER_INGOT("silver_ingot", Rarity.COMMON, 64),
    STEEL_INGOT("steel_ingot", Rarity.COMMON, 64),
    TIN_INGOT("tin_ingot", Rarity.COMMON, 64),
    URANIUM_INGOT("uranium_ingot", Rarity.COMMON, 64),
    BRONZE_PLATE("bronze_plate", Rarity.COMMON, 64),
    COPPER_PLATE("copper_plate", Rarity.COMMON, 64),
    GOLD_PLATE("gold_plate", Rarity.COMMON, 64),
    IRON_PLATE("iron_plate", Rarity.COMMON, 64),
    LAPIS_PLATE("lapis_plate", Rarity.COMMON, 64),
    LEAD_PLATE("lead_plate", Rarity.COMMON, 64),
    OBSIDIAN_PLATE("obsidian_plate", Rarity.COMMON, 64),
    STEEL_PLATE("steel_plate", Rarity.COMMON, 64),
    TIN_PLATE("tin_plate", Rarity.COMMON, 64),
    DENSE_BRONZE_PLATE("dense_bronze_plate", Rarity.COMMON, 64),
    DENSE_COPPER_PLATE("dense_copper_plate", Rarity.COMMON, 64),
    DENSE_GOLD_PLATE("dense_gold_plate", Rarity.COMMON, 64),
    DENSE_IRON_PLATE("dense_iron_plate", Rarity.COMMON, 64),
    DENSE_LAPIS_PLATE("dense_lapis_plate", Rarity.COMMON, 64),
    DENSE_LEAD_PLATE("dense_lead_plate", Rarity.COMMON, 64),
    DENSE_OBSIDIAN_PLATE("dense_obsidian_plate", Rarity.COMMON, 64),
    DENSE_STEEL_PLATE("dense_steel_plate", Rarity.COMMON, 64),
    DENSE_TIN_PLATE("dense_tin_plate", Rarity.COMMON, 64),
    BRONZE_CASING("bronze_casing", Rarity.COMMON, 64),
    COPPER_CASING("copper_casing", Rarity.COMMON, 64),
    GOLD_CASING("gold_casing", Rarity.COMMON, 64),
    IRON_CASING("iron_casing", Rarity.COMMON, 64),
    LEAD_CASING("lead_casing", Rarity.COMMON, 64),
    STEEL_CASING("steel_casing", Rarity.COMMON, 64),
    TIN_CASING("tin_casing", Rarity.COMMON, 64),
    ASHES("ashes", Rarity.COMMON, 64),
    IRIDIUM_ORE("iridium_ore", Rarity.RARE, 64),
    IRIDIUM_SHARD("iridium_shard", Rarity.UNCOMMON, 64),
    RESIN("resin", Rarity.COMMON, 64),
    SLAG("slag", Rarity.COMMON, 64),
    IODINE("iodine", Rarity.COMMON, 64),
    WATER_SHEET("water_sheet", Rarity.COMMON, 64),
    LAVA_SHEET("lava_sheet", Rarity.COMMON, 64),
    RUBBER("rubber", Rarity.COMMON, 64),
    CIRCUIT("circuit", Rarity.COMMON, 64),
    ADVANCED_CIRCUIT("advanced_circuit", Rarity.UNCOMMON, 64),
    ALLOY("alloy", Rarity.COMMON, 64),
    IRIDIUM("iridium", Rarity.RARE, 64),
    COIL("coil", Rarity.COMMON, 64),
    ELECTRIC_MOTOR("electric_motor", Rarity.COMMON, 64),
    HEAT_CONDUCTOR("heat_conductor", Rarity.COMMON, 64),
    COPPER_BOILER("copper_boiler", Rarity.COMMON, 64),
    FUEL_ROD("fuel_rod", Rarity.COMMON, 64),
    TIN_CAN("tin_can", Rarity.COMMON, 64),
    SMALL_POWER_UNIT("small_power_unit", Rarity.COMMON, 64),
    POWER_UNIT("power_unit", Rarity.COMMON, 64),
    CARBON_FIBRE("carbon_fibre", Rarity.COMMON, 64),
    CARBON_MESH("carbon_mesh", Rarity.COMMON, 64),
    CARBON_PLATE("carbon_plate", Rarity.COMMON, 64),
    COAL_BALL("coal_ball", Rarity.COMMON, 64),
    COAL_BLOCK("coal_block", Rarity.COMMON, 64),
    COAL_CHUNK("coal_chunk", Rarity.COMMON, 64),
    INDUTRIAL_DIAMOND("industrial_diamond", Rarity.COMMON, 64),
    PLANT_BALL("plant_ball", Rarity.COMMON, 64),
    BIO_CHAFF("bio_chaff", Rarity.COMMON, 64),
    SCRAP("scrap", Rarity.COMMON, 64),
    SCRAP_BOX("scrap_box", Rarity.COMMON, 64),
    CF_POWDER("cf_powder", Rarity.COMMON, 64),
    PELLET("pellet", Rarity.COMMON, 64),
    RAW_CRYSTAL_MEMORY("raw_crystal_memory", Rarity.COMMON, 64),
    IRON_SHAFT("iron_shaft", Rarity.COMMON, 64),
    STEEL_SHAFT("steel_shaft", Rarity.COMMON, 64),
    WOODEN_ROTOR_BLADE("wooden_rotor_blade", Rarity.COMMON, 64),
    IRON_ROTOR_BLADE("iron_rotor_blade", Rarity.COMMON, 64),
    STEEL_ROTOR_BLADE("steel_rotor_blade", Rarity.COMMON, 64),
    CARBON_ROTOR_BLADE("carbon_rotor_blade", Rarity.COMMON, 64),
    STEAM_TURBINE_BLADE("steam_turbine_blade", Rarity.COMMON, 64),
    STEAM_TURBINE("steam_turbine", Rarity.COMMON, 64),
    COIN("coin", Rarity.COMMON, 64),
    BRONZE_ROTOR_BLADE("bronze_rotor_blade", Rarity.COMMON, 64),
    BRONZE_SHAFT("bronze_shaft", Rarity.COMMON, 64),
    TRITIUM_FUEL_ROD("tritium_fuel_rod", Rarity.COMMON, 64),
    COFFEE_BEANS("coffee_beans", Rarity.COMMON, 64),
    COFFEE_POWDER("coffee_powder", Rarity.COMMON, 64),
    FERTILIZER("fertilizer", Rarity.COMMON, 64),
    GRIN_POWDER("grin_powder", Rarity.COMMON, 64),
    HOPS("hops", Rarity.COMMON, 64),
    WEED("weed", Rarity.COMMON, 64),
    BOBS_YER_UNCLE_RANKS_BERRY("bobs_yer_uncle_ranks_berry", Rarity.COMMON, 64),
    OIL_BERRY("oil_berry", Rarity.COMMON, 64),
    MILK_WART("milk_wart", Rarity.COMMON, 64),
    SMALL_DIAMOND_DUST("small_diamond_dust", Rarity.COMMON, 64),
    ENDER_PEARL_DUST("ender_pearl_dust", Rarity.COMMON, 64),
    BROKEN_RUBBER_BOAT("broken_rubber_boat", Rarity.COMMON, 1),
    ELECTROLYZED_WATER_CELL("electrolyzed_water_cell", Rarity.COMMON, 64);

    private final String id;
    private final Rarity rarity;
    private final int stackSize;

    MaterialDefinition(String id, Rarity rarity, int stackSize) {
        this.id = id;
        this.rarity = rarity;
        this.stackSize = stackSize;
    }

    public String id() {
        return id;
    }

    public Item.Properties properties(Item.Properties properties) {
        return properties.rarity(rarity).stacksTo(stackSize);
    }
}
